version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx10g -Xms10g"
    networks:
      - elk
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - /mnt/elk:/usr/share/elasticsearch/data

  logstash:
    build: logstash/
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/plugins:/usr/share/logstash/plugins
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx4g -Xms4g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    ports:
      - ":5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml


networks:

  elk:
    driver: bridge
