version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx20g -Xms20g"
    networks:
      - elk
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - /mnt/elk:/usr/share/elasticsearch/data
      - /mnt/elk2:/usr/share/elasticsearch/data2

  kibana:
    build: kibana/
    ports:
      - ":5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml


networks:

  elk:
    driver: bridge
